apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: ss-storage-class
provisioner: com.mapr.csi-kdf # com.mapr.csi-kdf
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  labels:
    app: datacollector
spec:
  ports:
  - port: 18630
    targetPort: 18630
    name: ui
  clusterIP: None
  selector:
    app: datacollector
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datacollector
spec:
  serviceName: "datacollector"
  replicas: 1
  selector:
    matchLabels:
      app: datacollector  
  template:
    metadata:
      labels:
        app: datacollector
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-datacollector-data",
            "image": "busybox",
            "command": ["sh", "-c", "chown -R admin /data /opt/streamsets-datacollector/streamsets-libs"],
            "volumeMounts": [
              {"name": "data", "mountPath": "/data", "subPath": "data"},
              {"name": "data", "mountPath": "/opt/streamsets-datacollector/streamsets-libs", "subPath": "stagelibs"}
            ]
          }
        ]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: datacollector
        image: streamsets/datacollector
        # resources:
        #   requests:
        #     memory: "4Gi"
        #     cpu: "2"
        #   limits:
        #     memory: "4Gi"
        #     cpu: "2"        
        ports:
        - containerPort: 18630
          name: ui
        readinessProbe:
          exec:
            command: ["curl", "127.0.0.1:18630/public-rest/ping"]
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: data
          mountPath: /opt/streamsets-datacollector/streamsets-libs
          subPath: stagelibs
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: ss-storage-class
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi