---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2020-07-24T22:13:50Z"
  name: default
  resourceVersion: "5023"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/default
  uid: 55d1c717-dbc9-4d5e-8656-c95f21bb8ca8
parameters:
  cldbHosts: 10.20.30.137:7222
  cluster: hcp.mapr.cluster
  csi.storage.k8s.io/provisioner-secret-name: mapr-user-secret
  csi.storage.k8s.io/provisioner-secret-namespace: mapr-csi
  csiNodePublishSecretName: mapr-ticket-secret
  csiNodePublishSecretNamespace: mapr-csi
  mountPrefix: /mapr-csi
  namePrefix: k8s-2-
  platinum: "true"
  restServers: 10.20.30.137:8443
  securityType: secure
provisioner: com.mapr.csi-kdf
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: Service
metadata:
  name: datacollector
  labels:
    app: datacollector
spec:
  ports:
  - port: 18630
    targetPort: 18630
    name: ui
  clusterIP: None
  selector:
    app: datacollector
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datacollector
spec:
  serviceName: "datacollector"
  replicas: 1
  selector:
    matchLabels:
      app: datacollector  
  template:
    metadata:
      labels:
        app: datacollector
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-datacollector-data",
            "image": "busybox",
            "command": ["sh", "-c", "chown -R 20159 /data /opt/streamsets-datacollector/streamsets-libs"],
            "volumeMounts": [
              {"name": "data", "mountPath": "/data", "subPath": "data"},
              {"name": "data", "mountPath": "/opt/streamsets-datacollector/streamsets-libs", "subPath": "stagelibs"}
            ]
          }
        ]'
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: datacollector
        image: streamsets/datacollector
        ports:
        - containerPort: 18630
        env:
        - name: SDC_JAVA_OPTS
          value: "-Dmaprlogin.password.enabled=true"
          name: ui
        readinessProbe:
          exec:
            command: ["curl", "127.0.0.1:18630/public-rest/ping"]
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        - name: data
          mountPath: /opt/streamsets-datacollector/streamsets-libs
          subPath: stagelibs
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi